# Generated by Django 2.1.9 on 2019-06-14 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
