# Generated by Django 2.1.9 on 2019-06-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='highlighted',
            field=models.TextField(default=''),
        ),
    ]
