# Generated by Django 2.1.9 on 2019-06-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190614_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
