# Generated by Django 2.1.9 on 2019-06-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_document_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='transactions',
            field=models.TextField(default=''),
        ),
    ]
