<template>
    <div class="container">
        <SearchBar @termChange="onTermChange"></SearchBar>
        <div class="row">
            <!-- video received from the onVideoSelect should reach VideoDetail -->
            <VideoDetail :video="selectedVideo"></VideoDetail>
            <!-- v-bind:videos ensures that VideoList component has access to property videos from App Component-->
            <!-- left hand is for child and right hand is for parent -->
            <!-- Whenever videos in parent is updated. Rerender the VideoList with updated videos -->
            <!-- <VideoList v-bind:videos="videos"></VideoList> --><!-- Shorthand syntax -->
            <VideoList @videoSelect="onVideoSelect" :videos="videos"></VideoList>
        </div>
    </div>
</template>

<script>
import axios from 'axios';
import SearchBar from './components/SearchBar';
import VideoList from './components/VideoList';
import VideoDetail from './components/VideoDetail';

const API_KEY = 'AIzaSyAm2_Dm5GqZmvs6S6kWH1UyS3zyPas52pU';

export default {
    name: 'App',
    components: {
        SearchBar,
        VideoList,
        VideoDetail
    },
    // ES 2015 Syntax
    data() {
        return {
            videos: [],
            selectedVideo: null
        };
    },
    methods: {
        // onTermChange: function(event) {
        //
        // }

        //ES 2015 Syntax
        // Generated by SearchBar
        onTermChange(searchTerm) {
            // console.log("App: " + searchTerm);
            axios.get('https://www.googleapis.com/youtube/v3/search', {
                params: {
                    key: API_KEY,
                    type: 'video',
                    part: 'snippet',
                    q: searchTerm
                }
            }).then(response => {
                // console.log(response);
                this.videos = response.data.items;
            });
        },

        // Generated by VideoList
        onVideoSelect(video) {
            this.selectedVideo = video;
        }
    }

};
</script>