# Generated by Django 2.1.9 on 2019-06-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_extractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractor',
            name='reference',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
