export default {
  raw_trades: String.raw`[
	{
		"trade_date": "06/19/18",
		"setl_date": "06/20/18",
		"mkt": "3",
		"cap": "1",
		"symbol": null,
		"trade_type": "BUY",
		"trade_qty": "10",
		"trade_rate": "$.33",
		"acct_type": "Margin",
		"marker_principal": "PRINCIPAL",
		"principal": "$330.00",
		"option": "CALL PBR 01/18/19 15",
		"opt_type": "CALL",
		"opt_name": "PBR",
		"expiry_date": "01/18/19",
		"strike_price": "15",
		"scrip_commission_fee": "PETROLEO BRASILEIRO SA COMMISSION $1.50\nOPEN CONTRACT OPT REG FEE $0.17",
		"marker_net_amount": "NET AMOUNT",
		"net_amount": "$331.67"
	},
	{
		"trade_date": "06/19/18",
		"setl_date": "06/20/18",
		"mkt": "3",
		"cap": "1",
		"symbol": null,
		"trade_type": "BUY",
		"trade_qty": "10",
		"trade_rate": "$.33",
		"acct_type": "Margin",
		"marker_principal": "PRINCIPAL",
		"principal": "$330.00",
		"option": "CALL PBR 01/18/19 15",
		"opt_type": "CALL",
		"opt_name": "PBR",
		"expiry_date": "01/18/19",
		"strike_price": "15",
		"scrip_commission_fee": "PETROLEO BRASILEIRO SA COMMISSION $1.50\nOPEN CONTRACT OPT REG FEE $0.17",
		"marker_net_amount": "NET AMOUNT",
		"net_amount": "$331.67"
	},
	{
		"trade_date": "06/19/18",
		"setl_date": "06/20/18",
		"mkt": "3",
		"cap": "1",
		"symbol": null,
		"trade_type": "BUY",
		"trade_qty": "129",
		"trade_rate": "$.33",
		"acct_type": "Margin",
		"marker_principal": "PRINCIPAL",
		"principal": "$4,257.00",
		"option": "CALL PBR 01/18/19 15",
		"opt_type": "CALL",
		"opt_name": "PBR",
		"expiry_date": "01/18/19",
		"strike_price": "15",
		"scrip_commission_fee": "PETROLEO BRASILEIRO SA COMMISSION $19.35\nOPEN CONTRACT OPT REG FEE $2.15",
		"marker_net_amount": "NET AMOUNT",
		"net_amount": "$4,278.50"
	},
	{
		"trade_date": "06/19/18",
		"setl_date": "06/20/18",
		"mkt": "3",
		"cap": "1",
		"symbol": null,
		"trade_type": "BUY",
		"trade_qty": "14",
		"trade_rate": "$.33",
		"acct_type": "Margin",
		"marker_principal": "PRINCIPAL",
		"principal": "$462.00",
		"option": "CALL PBR 01/18/19 15",
		"opt_type": "CALL",
		"opt_name": "PBR",
		"expiry_date": "01/18/19",
		"strike_price": "15",
		"scrip_commission_fee": "PETROLEO BRASILEIRO SA COMMISSION $2.10\nOPEN CONTRACT OPT REG FEE $0.23",
		"marker_net_amount": "NET AMOUNT",
		"net_amount": "$464.33"
	},
	{
		"trade_date": "06/19/18",
		"setl_date": "06/20/18",
		"mkt": "3",
		"cap": "4",
		"symbol": null,
		"trade_type": "BUY",
		"trade_qty": "18",
		"trade_rate": "$.33",
		"acct_type": "Margin",
		"marker_principal": "PRINCIPAL",
		"principal": "$594.00",
		"option": "CALL PBR 01/18/19 15",
		"opt_type": "CALL",
		"opt_name": "PBR",
		"expiry_date": "01/18/19",
		"strike_price": "15",
		"scrip_commission_fee": "PETROLEO BRASILEIRO SA COMMISSION $11.20\nOPEN CONTRACT OPT REG FEE $0.30",
		"marker_net_amount": "NET AMOUNT",
		"net_amount": "$605.50"
	},
	{
		"trade_date": "06/19/18",
		"setl_date": "06/20/18",
		"mkt": "3",
		"cap": "4",
		"symbol": null,
		"trade_type": "SELL",
		"trade_qty": "7",
		"trade_rate": "$1.42",
		"acct_type": "Margin",
		"marker_principal": "PRINCIPAL",
		"principal": "$994.00",
		"option": "CALL P 01/18/19 8",
		"opt_type": "CALL",
		"opt_name": "P",
		"expiry_date": "01/18/19",
		"strike_price": "8",
		"scrip_commission_fee": "PANDORA MEDIA INC COMMISSION $9.55\nCLOSING CONTRACT OPT REG FEE\nFEE\n$0.12\n0.02",
		"marker_net_amount": "NET AMOUNT",
		"net_amount": "$984.31"
	},
	{
		"trade_date": "06/19/18",
		"setl_date": "06/20/18",
		"mkt": "3",
		"cap": "1",
		"symbol": null,
		"trade_type": "SELL",
		"trade_qty": "93",
		"trade_rate": "$1.42",
		"acct_type": "Margin",
		"marker_principal": "PRINCIPAL",
		"principal": "$13,206.00",
		"option": "CALL P 01/18/19 8",
		"opt_type": "CALL",
		"opt_name": "P",
		"expiry_date": "01/18/19",
		"strike_price": "8",
		"scrip_commission_fee": "PANDORA MEDIA INC COMMISSION $13.95\nCLOSING CONTRACT FINRA TAF\nOPT REG FEE\nFEE\n$0.19\n1.55\n0.18",
		"marker_net_amount": "NET AMOUNT",
		"net_amount": "$13,190.13"
	},
	{
		"trade_date": "06/19/18",
		"setl_date": "06/20/18",
		"mkt": "3",
		"cap": "4",
		"symbol": null,
		"trade_type": "BUY",
		"trade_qty": "9",
		"trade_rate": "$.33",
		"acct_type": "Margin",
		"marker_principal": "PRINCIPAL",
		"principal": "$297.00",
		"option": "CALL PBR 01/18/19 15",
		"opt_type": "CALL",
		"opt_name": "PBR",
		"expiry_date": "01/18/19",
		"strike_price": "15",
		"scrip_commission_fee": "PETROLEO BRASILEIRO SA COMMISSION $1.35\nOPEN CONTRACT OPT REG FEE $0.15",
		"marker_net_amount": "NET AMOUNT",
		"net_amount": "$298.50"
	},
	{
		"trade_date": "06/19/18",
		"setl_date": "06/21/18",
		"mkt": "6",
		"cap": "1",
		"symbol": "HMNY",
		"trade_type": "SELL",
		"trade_qty": "20,000",
		"trade_rate": "$.35",
		"acct_type": "Margin",
		"marker_principal": "PRINCIPAL",
		"principal": "$7,000.00",
		"option": null,
		"opt_type": null,
		"opt_name": null,
		"expiry_date": null,
		"strike_price": null,
		"scrip_commission_fee": "HELIOS AND MATHESON ANALYTICS INC COMMISSION $3.95\nFINRA TAF\nFEE\n$2.38\n0.10",
		"marker_net_amount": "NET AMOUNT",
		"net_amount": "$6,993.57"
	},
	{
		"trade_date": "06/19/18",
		"setl_date": "06/20/18",
		"mkt": "3",
		"cap": "4",
		"symbol": null,
		"trade_type": "BUY",
		"trade_qty": "10",
		"trade_rate": "$.28",
		"acct_type": "Margin",
		"marker_principal": "PRINCIPAL",
		"principal": "$280.00",
		"option": "CALL PBR 01/18/19 15",
		"opt_type": "CALL",
		"opt_name": "PBR",
		"expiry_date": "01/18/19",
		"strike_price": "15",
		"scrip_commission_fee": "PETROLEO BRASILEIRO SA COMMISSION $10.00\nOPEN CONTRACT OPT REG FEE $0.17",
		"marker_net_amount": "NET AMOUNT",
		"net_amount": "$290.17"
	}
]`,
  raw_trades_schema: String.raw`[
	{
		"src": "trade_date",
		"srctype": "datetime64[ns]",
		"select": true,
		"dst": "trade_date"
	},
	{
		"src": "setl_date",
		"srctype": "datetime64[ns]",
		"select": true,
		"dst": "setl_date"
	},
	{
		"src": "mkt",
		"srctype": "object",
		"select": true,
		"dst": "mkt"
	},
	{
		"src": "cap",
		"srctype": "object",
		"select": true,
		"dst": "cap"
	},
	{
		"src": "symbol",
		"srctype": "object",
		"select": true,
		"dst": "symbol"
	},
	{
		"src": "trade_type",
		"srctype": "object",
		"select": true,
		"dst": "trade_type"
	},
	{
		"src": "trade_qty",
		"srctype": "object",
		"select": true,
		"dst": "trade_qty"
	},
	{
		"src": "trade_rate",
		"srctype": "object",
		"select": true,
		"dst": "trade_rate"
	},
	{
		"src": "acct_type",
		"srctype": "object",
		"select": true,
		"dst": "acct_type"
	},
	{
		"src": "marker_principal",
		"srctype": "object",
		"select": true,
		"dst": "marker_principal"
	},
	{
		"src": "principal",
		"srctype": "object",
		"select": true,
		"dst": "principal"
	},
	{
		"src": "option",
		"srctype": "object",
		"select": true,
		"dst": "option"
	},
	{
		"src": "opt_type",
		"srctype": "object",
		"select": true,
		"dst": "opt_type"
	},
	{
		"src": "opt_name",
		"srctype": "object",
		"select": true,
		"dst": "opt_name"
	},
	{
		"src": "expiry_date",
		"srctype": "datetime64[ns]",
		"select": true,
		"dst": "expiry_date"
	},
	{
		"src": "strike_price",
		"srctype": "object",
		"select": true,
		"dst": "strike_price"
	},
	{
		"src": "scrip_commission_fee",
		"srctype": "object",
		"select": true,
		"dst": "scrip_commission_fee"
	},
	{
		"src": "marker_net_amount",
		"srctype": "object",
		"select": true,
		"dst": "marker_net_amount"
	},
	{
		"src": "net_amount",
		"srctype": "object",
		"select": true,
		"dst": "net_amount"
	}
]`,
}
